"""Global configuration for topology optimization."""

N = 32
A_GROUP_SIZE = 20
B_GROUP_SIZE = 12
PORTS_PER_CHIP = 9
DEFAULT_RANDOM_SEED = 42

TRAFFIC_VOLUME = 1.0

ROUTING_STRATEGY = "adaptive_multipath"
MAX_SHORTEST_PATHS = 16
EXTRA_HOPS = 1
ROUTING_ITERATIONS = 4

SEARCH_STRATEGY = "simulated_annealing"
REWIRE_EDGES = 6
SWAP_EDGES = 3
INITIAL_TEMPERATURE = 6.0
COOLING_RATE = 0.99
DISCONNECTED_PENALTY = 1000.0
STAGNATION_LIMIT = 300
ALLOW_INTRA_GROUP = False
