"""Global configuration for topology optimization."""

N = 128
A_GROUP_SIZE = 64
B_GROUP_SIZE = 64
PORTS_PER_CHIP = 12
DEFAULT_RANDOM_SEED = 42

TRAFFIC_VOLUME = 1.0

RESUME_STATE_PATH = "optimization_result.json"
MIN_ITERATIONS = 200
EARLY_STOP_PATIENCE = 200

ROUTING_STRATEGY = "adaptive_multipath"
MAX_SHORTEST_PATHS = 16
EXTRA_HOPS = 1
ROUTING_ITERATIONS = 4

SEARCH_STRATEGY = "simulated_annealing"
REWIRE_EDGES = 12
SWAP_EDGES = 6
INITIAL_TEMPERATURE = 9.0
COOLING_RATE = 0.995
CANDIDATE_POOL = 3
DISCONNECTED_PENALTY = 1000.0
STAGNATION_LIMIT = 300
ALLOW_INTRA_GROUP = True
